config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :destinations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/destination.rb
class Destination < ApplicationRecord
  validates :city, :country, :attraction, :description, :image, presence: true
  validates :city, :country, :attraction, length: { in: 2..100 }
  validates :description, length: { in: 3..2000 }

  has_one_attached :image do |attachable|
      attachable.variant :thumb, resize_to_limit: [400,400]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  def index
    @destination = Destination.all
  end

  def show
  end

  def new
    @destination = Destination.new
  end

  def create
    #whitelisting the params
    @destination = Destination.new(destination_params)
    #save to db
    if @destination.save
      flash[:notice] = 'Destination saved succesfully'
      redirect_to destination_path(@destination)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @destination.update(destination_params)
      flash[:notice] = 'Destination was updated sucessfully'
      redirect_to @destination
    else
      render 'edit'
    end
  end

  def destroy
    @destination.destroy
    flash[:notice] = 'Destination was deleted successfully'
    redirect_to destinations_path
  end
  
  private
  
  def set_destination
    @destination = Destination.find(params[:id])
  end

  def destination_params
    params.require(:destination).permit(:image, :country, :city, :attraction, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/destinations/edit.html.erb
<h1 class="my-4 text-center">Edit destination details</h1>
<div class="text-center">
  <%= link_to 'Delete', destination_path(@destination), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this article?"}, class: "btn btn-outline-light btn-md" %>
  <%= link_to 'Back', destination_path, class: "btn btn-outline-light btn-md" %>
</div>
<div class="container mt-4">
  <% if @destination.errors.any? %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <h4>The following errors occured:</h4>
      <% @destination.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
    <% end %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>
<div class ="col d-flex justify-content-center" style= "margin-top: 2em">
  <div class="card text-bg-dark border-info" style="width: 80%">
    <%= form_with(model: @destination, data: { turbo: false }, local: true) do |f| %>
    <div style="height: 60vh">
        <% if @destination.image.variant(:thumb) %>
        <%= image_tag @destination.image.variant(:thumb), class: "card-img-side opacity-25" %>
        <% end %>
        <div class="card-img-overlay mb-5" style="overflow-y: auto;">
          <p class="card-text">
            <%= f.label :image %> <br>
            <%= f.file_field :image %>
          </p>
          <p class="card-text">
            <%= f.label :country%> <br>
            <%= f.text_field :country%>
          </p>
          <p class="card-text">
            <%= f.label :city%> <br>
            <%= f.text_field :city%>
          </p>
          <p class="card-text">  
            <%= f.label :attraction%> <br>
            <%= f.text_field :attraction%></p>
          <p>
          <p class="card-text">  
            <%= f.label :description%> <br>
            <%= f.text_area :description%></p>
          <p>
          <p>
            <%= f.submit %>
          </p>
      </div>
    </div>
    <% end %>
    <div class="card-footer border-info text-center fst-italic">
      <small class="text-info"> Created: <%= time_ago_in_words(@destination.created_at) %> ago </small>
    </div>
  </div>
</div>

app/views/destinations/index.html.erb
<h1 class="my-4 text-center">Our recommendations</h1>
  <div class="text-center">
    <%= link_to 'Create new destination', new_destination_path, class: "btn btn-outline-light btn-md" %>
    <%= link_to 'Back to homepage', root_path, class: "btn btn-outline-light btn-md" %>
  </div>
  <div class="row row-cols-2 row-cols-md-4 g-4 m-4">
    <% @destination.each do |destination| %>
      <div class="col">
        <div class="card h-100 text-bg-dark border-info mb-3" style="max-width: 25rem">
          <% if destination.image.variant(:thumb)%>
            <%= image_tag destination.image.variant(:thumb), class: "card-img-top card border-info" %>
          <% end %>
          <div class="card-body">
            <h6 class="card-title fw-light">Country: <%= destination.country %></h6>
            <h6 class="card-title fw-light">City: <%= destination.city %></h6>
            <h6 class="card-text fw-light ">Attraction: <%= destination.attraction %></h6>
            <div class="text-center">
              <%= link_to 'View', destination_path(destination), class: "btn btn-outline-light btn-sm" %>
              <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-outline-light btn-sm" %>
              <%= link_to 'Delete', destination_path(destination), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this article?"}, class: "btn btn-outline-light btn-sm" %> 
            </div>  
          </div>
        <div class="card-footer border-info text-center fst-italic">
          <small class="text-info"> Created: <%= time_ago_in_words(destination.created_at) %> ago</small>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/views/destinations/new.html.erb
<h1 class="my-4 text-center">Enter new destination</h1>
<div class="text-center">
  <%= link_to 'Back', destinations_path, class: "btn btn-outline-light btn-md" %>
</div>
<div class="container mt-4">
  <% if @destination.errors.any? %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <h4>The following errors occured:</h4>
      <% @destination.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

<div class ="col d-flex justify-content-center" style= "margin-top: 2em">
  <div class="card text-bg-dark border-info" style="width: 80%">
    <%= form_with(model: @destination, data: { turbo: false }, local: true) do |f| %>
      <div style="min-height: 50vh">
        <div class="card-img-overlay" style="position: relative">
          <p class="card-text">
            <%= f.label :image %> <br>
            <%= f.file_field :image %>
          </p>
          <p class="card-text">
            <%= f.label :country%> <br>
            <%= f.text_field :country%>
          </p>
          <p class="card-text">
            <%= f.label :city%> <br>
            <%= f.text_field :city%>
          </p>
          <p class="card-text">  
            <%= f.label :attraction%> <br>
            <%= f.text_field :attraction%></p>
          <p>
          <p class="card-text">  
            <%= f.label :description%> <br>
            <%= f.text_area :description%></p>
          <p>
          <p>
            <%= f.submit %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/destinations/show.html.erb
<h1 class="my-4 text-center">Showing destination details</h1>
<div class="text-center">
  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-outline-light btn-md"%>
  <%= link_to 'Delete', destination_path(@destination), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this article?"}, class: "btn btn-outline-light btn-md" %>
  <%= link_to 'Back', destinations_path, class: "btn btn-outline-light btn-md" %>
</div>
<div class ="col d-flex justify-content-center" style= "margin-top: 2em">
  <div class="card text-bg-dark border-info" style="width: 80%">
    <div style="height: 60vh">
        <% if @destination.image.variant(:thumb) %>
        <%= image_tag @destination.image.variant(:thumb), class: "card-img-side opacity-25" %>
        <% end %>
        <div class="card-img-overlay mb-5" style="overflow-y: auto;">
          <p class="card-text">Country: <%=@destination.country %></p>
          <p class="card-text">City: <%=@destination.city %></p>
          <p class="card-text">Attraction: <%=@destination.attraction %></p>
          <p class="card-text">Description: <br> <%=@destination.description %></p>
          <p>
      </div>
    </div>
    <div class="card-footer border-info text-center fst-italic">
      <small class="text-info"> Created: <%= time_ago_in_words(@destination.created_at) %> ago </small>
    </div>
  </div>
</div>

app/views/layouts/_flashmsg.html.erb
<div class="container mt-4">
<% flash.each do |name, message| %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 text-white text-center">
    <small
      >Copyright &copy; <%= link_to "Alex Barron",
      "https://lex-aeterna.github.io/", class: "text-white text-decoration-none"
      %></small
    >
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <%= link_to "Traveldations", root_path,  class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Homepage', root_path, class: "nav-link active text-white" %>
        </li>
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Destinations
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add a new destination", new_destination_path,  class: "dropdown-item text-dark"%></li>
            <li><%= link_to "View all destinations", destinations_path,  class: "dropdown-item text-dark"%></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link active text-white"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Traveldations</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag "turbo", type: "module" %>
  </head>
  <body>
    <div id="wrap">
    <%= render 'layouts/navigation'%> 
    <%= render 'layouts/flashmsg'%>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="my-4 text-center">About</h1>

<div class="container text-center text-white mt-4">
  <p>
    Traveldations is a project featuring sample CRUD operations using Ruby on
    Rails and Bootstrap framework. <%= link_to 'Add', new_destination_path,
    class: "btn btn-outline-light btn-sm" %> your travel recommendation today!
  </p>
</div>

<div class="text-center">
  <%= link_to 'Back to the homepage', root_path, class: "btn btn-outline-light
  btn-md" %>
</div>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="text-center text-white">
  <h1 class="cover-heading">Traveldations</h1>
  <h4 class="lead">Small world, big ideas</h4>
  <p class="lead">
    <%= link_to 'Take me somewhere', destinations_path, class: "btn btn-outline-light btn-lg" %>
    <%= link_to 'About', about_path, class: "btn btn-outline-light btn-lg"  %>
  </p>
</div>
</div>